---
title: "Cleaning the Polynesian Rat SNP raw data file"
author: "Grace Saville"
date: "16/05/2022"
output: pdf_document
---

```{r setup, include = FALSE}
library(formatR)
library(knitr)
opts_chunk$set(echo = TRUE)
opts_knit$set(root.dir = "C:/Users/airhe/OneDrive/Documents/Masters/Project 3/kiore-project")
```

```{r libraries, include = FALSE}
library(plyr)
library(reshape)
# getwd()
# setwd("C:/Users/airhe/OneDrive/Documents/Masters/Project 3/kiore-project")
```

# 1. Loading the data

```{r loading}
data <- read.delim("./data/Raw_data/Genotyping-007.010-01_SNP_Raw_data.tsv")
dim(data) #478 rows (specimens), 333 columns (SNP loci)
kable(t(data[1,1:17])) # SNP data in columns 17 to 333
```

```{r check}
class(data[5,17]) # character
kable(count(data$island.1)) #  how many samples from each island there are
# data[data$island.1 == "",1:17] # checking why 2 "island.1" cells are blank
kable(data[c(471,473),c(1,3,4,6,8:10)]) # the blanks are from Laos and Cambodia
data[471,"island.1"] <- "Mainland" # replacing the blanks with "Mainland"
data[473,"island.1"] <- "Mainland"

x <- data # keeping "data" as backup original
```

# 2. Tidying SNP order

* I'm doing this to make R evaluation easier (e.g when checking for counts it does not count A:G and G:A separately)
```{r SNP-arrangement}
dim(x) # 333 cols
# count(unlist(x[,17:333]))
x[x == "T:A"] <- "A:T"
x[x == "C:A"] <- "A:C"
x[x == "G:A"] <- "A:G" 
x[x == "T:C"] <- "C:T"
x[x == "G:C"] <- "C:G"
x[x == "G:T"] <- "T:G"
kable(count(unlist(x[,17:333]))) # checking success
```

# 3. Removing SNP columns with no variation (invariant/monomorphic)

```{r invariant-column-search}
ncol(x) #333
monocols <- integer() # empty vector for the for loop
for (i in 17:333) {
  z <- length(unique(x[, i])) # no. of unique values in the row
  if (z <= 3) {
    monocols <- append(monocols, i) # for TRUE z, add the column number to the vector
  }
  rm(z)
} 
# tried with z <= 2 but no result, therefore tried z <= 3
# checked the results manually below

monocols
for (i in monocols) {
  print(unique(x[,i]))
}
# none with only 1 unique SNP in each column ...? It's possible since the SNP loci 
# were selected for their differences, but double check this 
```

```{r column-deletion-1}
# x <- x[,-c(monocols)] # for removal of monomorphic columns if necessary

rm(i, monocols)
```

# 4. Removing columns (SNPs) with few samples

```{r removing-sparse-columns}
ncol(x) #333
percblank <- integer() # empty df for the for loop
for (i in 17:333) {
  y <- count(grepl("?", x[,i], fixed = TRUE)) # finds and counts freq of ?
  z <- signif((nrow(x)- y[1,2])/nrow(x)*100, 4) # percentage of ? in the column,
  # to 4 signif digits. I used the number of rows-false outcomes instead of the 
  # true outcomes because some rows have no "?"s and result in errors.
    if (z > 60) 
      {percblank <- append(percblank, i) 
    }
  rm(z)
  rm(y)
}

percblank
# checking:
# count(x[,212])
# 320/478
```

```{r column-deletion-2}
x <- x[,-c(percblank)] # removing columns listed above, with more than 60% missing data
rm(i, percblank)
```

# 5. Removing rows (specimens) with few samples

```{r removing-sparse-rows}
x2 <- data.table::transpose(x) # transposing the df temporarily since count() 
# doesn't work well on rows

ncol(x2) #478 specimens
percblank <- integer() # empty df for the for loop
for (i in 1:478) {
  y <- count(grepl("?", x2[,i], fixed = TRUE)) # finds and counts freq of "?"
  z <- signif((nrow(x2) - y[1,2]) / nrow(x2) * 100, 4) # percentage of ? in the 
  # specimen, to 4 signif digits. 
  # I used the no. rows-false outcomes instead of the true outcomes because 
  # some rows have no "?" and result in errors.
  if (z > 56)
    # 56 percent missing allowed because it gives 90% completeness (see below)
  {
    percblank <- append(percblank, i)
  }
  rm(z)
  rm(y)
}

percblank
# checking work:
# count(x2[17:298,171])
# 185/298
```

```{r row-deletion}
x <- x[-c(percblank),] # removing the rows that have too many "?" from the df
nrow(x) #379
```

# 6. Saving

```{r check-and-save}
# checking the % of all "?"s in the df:
z <- count(grepl("?", unlist(x), fixed = TRUE))
signif(z[2,2]/(z[1,2]+z[2,2])*100, 4) # 9.723% "?"
100 - 9.723 # 90.277% complete df, ideal point where there is more than 90% 
# completeness but not too many rows and columns removed (yet)

rm(i, percblank, x2, z)
# getwd()
# save(list=ls(all=TRUE), file=".RData") # save RDATA for later use if necessary
# write.csv(x, "./data/RStudio/ratsSNPs_halfclean.csv", row.names = FALSE)
```



