---
title: "Testing the Heterozygosity per Island"
author: "Grace Saville"
date: "01/02/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

# Preamble 

```{r libraries}
library(stringr)
library(dplyr)
getwd()
setwd("C:/Users/airhe/OneDrive/Documents/Masters/Project 3/kiore-project")
```

# Dataset loading

```{r loading data}
data <- read.csv("./data/ratsSNPs_clean.csv")

copy <- data # making a copy of the data
colnames(copy)
copy <- copy[,-c(2:16)] # removing unnecessary columns for this analysis
```

# Replaces SNP's with symbols for heterozygous and homozygous

```{r Setting up data}
dim(copy) # 370 rows 283 columns
str(copy)
unique(unlist(copy[,17:283])) # checking what SNP combinations are present
# "?"   "A:A" "G:G" "A:G" "T:T" "A:T" "C:C" "C:T" "T:G" "C:G" "A:C"

het <- c("A:G", "A:T", "C:T", "T:G", "C:G", "A:C") # vector of heterozygous combinations
hom <- c("G:G", "A:A", "C:C", "T:T") # vector of homozygous combinations

# Replacing specific combos
for (i in 1:nrow(copy)){
  copy[i,][copy[i,] %in% het] <- "E" 
  copy[i,][copy[i,] %in% hom] <- "O"
}

rm(i)

str(copy)
copy[copy == "?"] <- NA # replacing ? with NA's 
```

# Calculating heterozygous and homozygous totals per specimen

```{r totals per specimen}
o.freq <- vector()
e.freq <- vector()
na.freq <- vector()
for (i in 1:370) {
  x <- sum(grepl("O", copy[i,], fixed = TRUE)) # counting row O's
  o.freq <- append(o.freq, x) # adding sum to vector
  x <- sum(grepl("E", copy[i,], fixed = TRUE)) # counting row E's
  e.freq <- append(e.freq, x)
  x <- sum(is.na(copy[i,])) # counting row NA's
  na.freq <- append(na.freq, x)
  rm(x)
}

rm(i)

df <- data.frame(copy$island, o.freq, e.freq, na.freq) # making a df with the freq totals
perc.o <- round(as.vector((df$o.freq / (df$o.freq + df$e.freq)) * 100), digits = 3) # percentage without incl missing
df$perc.o <- perc.o
perc.missing <- round(as.vector((df$na.freq / (df$o.freq + df$e.freq + df$na.freq)) * 100), digits = 3) # percentage of missing data in row/specimen
df$perc.missing <- perc.missing

rm(perc.o, perc.missing)

str(df)
```

# Calculating heterozygous and homozygous totals per island

```{r totals per island}
data <- data[order(data$island, decreasing = FALSE),] # ordering df alphabetically by island
unique(data$island)
# sum(data$island.1 == "Mainland")
shortpopnames <- as.character(c(
  "aotea",
  "borneo",
  "cambodia",
  "grtmercury",   
  "halmaher",
  "hatutaa",
  "honuea",
  "kaikura",        
  "kamaka",
  "kayangel",
  "late",
  "luzon",
  "malenge",
  "mohotani",
  "motukawa",
  "newbrita",          
  "newguine",
  "normanby",
  "rakiura",
  "reiono",                
  "rimatuu",
  "slipper",
  "southland",
  "sulawesi",               
  "tahanea",
  "thailand",
  "wake")            
)

# splitting the data df into df objects by island:
for (i in 1:length(shortpopnames)) {
  y <- as.vector(grep(shortpopnames[i], copy[,1], ignore.case = TRUE, value = FALSE))
  assign(paste(shortpopnames[i]), copy[y,])
}
rm(y, i)

# making a "mainland" df:
mainland <- rbind(cambodia, luzon, thailand)
rm(cambodia, luzon, thailand)
shortpopnames
shortpopnames <- shortpopnames[-c(3, 12, 26)]
shortpopnames <- append(shortpopnames, "mainland")

# double checking the dfs have the correct specimens per island:
for (i in 1:25) {
  print(shortpopnames[i])
  y <- get(shortpopnames[i])
  print(y[,1])
}

# counting values:
sums <- data.frame()
for (i in 1:length(shortpopnames)) {
  o <- sum(grepl("O", unlist(get(shortpopnames[i])), fixed = TRUE)) # counting row O's
  e <- sum(grepl("E", unlist(get(shortpopnames[i])), fixed = TRUE)) # counting row E's
  na <- sum(is.na(get(shortpopnames[i]))) # counting row NA's
  vec <- as.vector(c(shortpopnames[i], o, e, na))
  sums <- rbind(sums, vec)
}

colnames(sums) <- c("island", "o.freq", "e.freq", "na.freq")
str(sums)
sums$o.freq <- as.integer(sums$o.freq)
sums$e.freq <- as.integer(sums$e.freq)
sums$na.freq <- as.integer(sums$na.freq)

# calculating percentages:
perc.o <- round(as.vector((sums$o.freq / (sums$o.freq + sums$e.freq)) * 100), digits = 3) # percentage without incl missing
sums$perc.o <- perc.o
perc.missing <- round(as.vector((sums$na.freq / (sums$o.freq + sums$e.freq + sums$na.freq)) * 100), digits = 3) # percentage of missing data in row/specimen
sums$perc.missing <- perc.missing

```

